In [2]:
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd
from google.colab import files
uploaded=files.upload()

Saving EmployeeBurnout1.csv to EmployeeBurnout1 (1).csv


In [3]:
data_set= pd.read_csv('EmployeeBurnout1.csv')
data_set.head()

Employee ID Date of Joining  Gender Company Type  \
0  fffe32003000360033003200       9/30/2008  Female      Service   
1      fffe3700360033003500      11/30/2008    Male      Service   
2  fffe31003300320037003900       3/10/2008  Female      Product   
3  fffe32003400380032003900       11/3/2008    Male      Service   
4  fffe31003900340031003600       7/24/2008  Female      Service   

  WFH Setup Available  Designation  Resource Allocation  Mental Fatigue Score  \
0                  No            2                  3.0                   3.8   
1                 Yes            1                  2.0                   5.0   
2                 Yes            2                  NaN                   5.8   
3                 Yes            1                  1.0                   2.6   
4                  No            3                  7.0                   6.9   

   Burn Rate  
0       0.16  
1       0.36  
2       0.49  
3       0.20  
4       0.52

In [4]:
data_set.isnull().sum()

Employee ID                0
Date of Joining            0
Gender                     0
Company Type               0
WFH Setup Available        0
Designation                0
Resource Allocation     1381
Mental Fatigue Score    2117
Burn Rate               1124
dtype: int64

In [5]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputerimputer= imputer.fit(data_set.iloc[:,6:9])
data_set.iloc[:,6:9]=imputer.transform(data_set.iloc[:,6:9])

In [6]:
data_set.isnull().sum()

Employee ID             0
Date of Joining         0
Gender                  0
Company Type            0
WFH Setup Available     0
Designation             0
Resource Allocation     0
Mental Fatigue Score    0
Burn Rate               0
dtype: int64

In [7]:
x= data_set.iloc[:,2:-1].values
print(x)

[['Female' 'Service' 'No' 2 3.0 3.8]
 ['Male' 'Service' 'Yes' 1 2.0 5.0]
 ['Female' 'Product' 'Yes' 2 4.481398287238523 5.8]
 ...
 ['Male' 'Service' 'Yes' 3 7.0 5.728187854407987]
 ['Female' 'Service' 'No' 2 5.0 5.9]
 ['Male' 'Product' 'No' 3 6.0 7.8]]


In [8]:
y= data_set.iloc[:,8].values
print(y)

[0.16 0.36 0.49 ... 0.72 0.52 0.61]


In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x= LabelEncoder()
x[:,0]= label_encoder_x.fit_transform(x[:,0])
x[:,1]= label_encoder_x.fit_transform(x[:,1])
x[:,2]= label_encoder_x.fit_transform(x[:,2])


In [10]:
print(x)

[[0 1 0 2 3.0 3.8]
 [1 1 1 1 2.0 5.0]
 [0 0 1 2 4.481398287238523 5.8]
 ...
 [1 1 1 3 7.0 5.728187854407987]
 [0 1 0 2 5.0 5.9]
 [1 0 0 3 6.0 7.8]]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

In [12]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [13]:
y_pred= regressor.predict(x_test)
x_pred= regressor.predict(x_train)
print(regressor.intercept_)

-0.06014439318020104


In [14]:
print(regressor.coef_)

[ 0.00598786 -0.00049692 -0.01536726  0.00826158  0.02945869  0.06426599]


In [15]:
print('Train Score: ', regressor.score(x_train, y_train))
print('Test Score: ', regressor.score(x_test, y_test))

Train Score:  0.8276327447678001
Test Score:  0.8420305813052529


In [16]:
import statsmodels.api as sm
x = sm.add_constant(x)
x=np.array(x, dtype=(float))
model = sm.OLS(y, x).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.831
Model:                            OLS   Adj. R-squared:                  0.831
Method:                 Least Squares   F-statistic:                 1.869e+04
Date:                Thu, 30 Nov 2023   Prob (F-statistic):               0.00
Time:                        12:54:18   Log-Likelihood:                 25363.
No. Observations:               22750   AIC:                        -5.071e+04
Df Residuals:                   22743   BIC:                        -5.066e+04
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0614      0.002    -28.315      0.0