In [419]:
import numpy as np
import pandas as pd
 
 

In [420]:
data= pd.read_csv("C:\\Users\\LAPTOP\\OneDrive - Faculty of Computers and Information\\EM.csv")


In [421]:
data.head()

Employee ID Date of Joining  Gender Company Type  \
0  fffe32003000360033003200       9/30/2008  Female      Service   
1      fffe3700360033003500      11/30/2008    Male      Service   
2  fffe31003300320037003900       3/10/2008  Female      Product   
3  fffe32003400380032003900       11/3/2008    Male      Service   
4  fffe31003900340031003600       7/24/2008  Female      Service   

  WFH Setup Available  Designation  Resource Allocation  Mental Fatigue Score  \
0                  No            2                  3.0                   3.8   
1                 Yes            1                  2.0                   5.0   
2                 Yes            2                  NaN                   5.8   
3                 Yes            1                  1.0                   2.6   
4                  No            3                  7.0                   6.9   

   Burn Rate  
0       0.16  
1       0.36  
2       0.49  
3       0.20  
4       0.52

In [422]:
data.describe()

Designation  Resource Allocation  Mental Fatigue Score     Burn Rate
count  22750.000000         21369.000000          20633.000000  21626.000000
mean       2.178725             4.481398              5.728188      0.452005
std        1.135145             2.047211              1.920839      0.198226
min        0.000000             1.000000              0.000000      0.000000
25%        1.000000             3.000000              4.600000      0.310000
50%        2.000000             4.000000              5.900000      0.450000
75%        3.000000             6.000000              7.100000      0.590000
max        5.000000            10.000000             10.000000      1.000000

In [423]:
data.isnull().sum()

Employee ID                0
Date of Joining            0
Gender                     0
Company Type               0
WFH Setup Available        0
Designation                0
Resource Allocation     1381
Mental Fatigue Score    2117
Burn Rate               1124
dtype: int64

In [424]:
data=data.drop("Employee ID",axis=1)
 

In [425]:
data.isnull().sum()

Date of Joining            0
Gender                     0
Company Type               0
WFH Setup Available        0
Designation                0
Resource Allocation     1381
Mental Fatigue Score    2117
Burn Rate               1124
dtype: int64

In [426]:
data = data.dropna(how='any',axis=0) 
 

In [427]:
dum=pd.get_dummies(data,drop_first=True)
dum.head()

Designation  Resource Allocation  Mental Fatigue Score  Burn Rate  \
0            2                  3.0                   3.8       0.16   
1            1                  2.0                   5.0       0.36   
3            1                  1.0                   2.6       0.20   
4            3                  7.0                   6.9       0.52   
5            2                  4.0                   3.6       0.29   

   Date of Joining_1/10/2008  Date of Joining_1/11/2008  \
0                          0                          0   
1                          0                          0   
3                          0                          0   
4                          0                          0   
5                          0                          0   

   Date of Joining_1/12/2008  Date of Joining_1/13/2008  \
0                          0                          0   
1                          0                          0   
3                          0                          0   
4                          0                          0   
5                          0                          0   

   Date of Joining_1/14/2008  Date of Joining_1/15/2008  ...  \
0                          0                          0  ...   
1                          0                          0  ...   
3                          0                          0  ...   
4                          0                          0  ...   
5                          0                          0  ...   

   Date of Joining_9/30/2008  Date of Joining_9/4/2008  \
0                          1                         0   
1                          0                         0   
3                          0                         0   
4                          0                         0   
5                          0                         0   

   Date of Joining_9/5/2008  Date of Joining_9/6/2008  \
0                         0                         0   
1                         0                         0   
3                         0                         0   
4                         0                         0   
5                         0                         0   

   Date of Joining_9/7/2008  Date of Joining_9/8/2008  \
0                         0                         0   
1                         0                         0   
3                         0                         0   
4                         0                         0   
5                         0                         0   

   Date of Joining_9/9/2008  Gender_Male  Company Type_Service  \
0                         0            0                     1   
1                         0            1                     1   
3                         0            1                     1   
4                         0            0                     1   
5                         0            1                     0   

   WFH Setup Available_Yes  
0                        0  
1                        1  
3                        1  
4                        0  
5                        1  

[5 rows x 372 columns]

In [428]:
##scaling for data
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()

dum= pd.DataFrame(standard_scaler.fit_transform(dum), columns=dum.columns)
print(dum.iloc[:,370]) 
 

0        0.725965
1        0.725965
2        0.725965
3        0.725965
4       -1.377477
           ...   
18585   -1.377477
18586   -1.377477
18587   -1.377477
18588    0.725965
18589   -1.377477
Name: Company Type_Service, Length: 18590, dtype: float64


In [429]:
cols = dum.shape[1]
x1 = dum.iloc[:, list(range(3)) + list(range(4, 372))]
y = dum.iloc[:,3]
 

In [430]:
x= np.matrix(x1.values)  
y= np.matrix(y.values)
y= y.reshape(-1,1)
  

In [431]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
 

In [432]:
## variance threshold

from sklearn.feature_selection import VarianceThreshold
from sklearn.metrics import mean_squared_error

from sklearn.linear_model import LinearRegression


variance_threshold  =.001 
selector = VarianceThreshold(threshold=variance_threshold)

X_train_selected = selector.fit_transform(X_train)
X_test_selected = selector.transform(X_test)

  

In [433]:
model = LinearRegression()
model.fit(X_train_selected, y_train)
y_pred = model.predict(X_test_selected)
print(y_pred )
 

[[-0.98070375]
 [-0.2222779 ]
 [-0.49432113]
 ...
 [-0.49356378]
 [ 1.50855042]
 [-0.56596136]]


In [434]:
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(y_test )


Mean Squared Error: 0.08047886860579534
[[-1.37707858]
 [-0.82108005]
 [-0.4672628 ]
 ...
 [-0.31562684]
 [ 2.16109387]
 [-0.31562684]]


In [435]:
score_test=model.score(X_test_selected  ,y_test)
print("test",score_test)
score_train=model.score(X_train_selected,y_train  )
print("train",score_train)

test 0.9185824574485179
train 0.9228615350724965


In [436]:
### select the most features is correlation with target output


import statsmodels.api as sm
X = sm.add_constant(x)
model = sm.OLS(y, X)
results = model.fit()

 

In [437]:
X_df = pd.DataFrame(X, columns=['const'] + [f'feature_{i}' for i in range(1, X.shape[1])])
p_values = results.pvalues[1:]   
feature_names = X_df.columns[1:]   
significant_features = [feature for feature, p_value in zip(feature_names, p_values) if p_value < 0.05]

print("Significant Features:", significant_features)

Significant Features: ['feature_1', 'feature_2', 'feature_3', 'feature_369', 'feature_371']


In [438]:
x2=x1[["Designation","Resource Allocation","Mental Fatigue Score","WFH Setup Available_Yes","Company Type_Service"]]
x_features_input=np.matrix(x2.values)
 

In [439]:
X_train, X_test, y_train, y_test = train_test_split(x_features_input, y, test_size=0.3, random_state=42)


In [440]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred )
 

[[-1.04366041]
 [-0.29192999]
 [-0.47959529]
 ...
 [-0.52667381]
 [ 1.5035972 ]
 [-0.60030523]]


In [441]:
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
 

Mean Squared Error: 0.0785945724424124


In [442]:
score_test=model.score(X_test   ,y_test)
print("test",score_test)
score_train=model.score(X_train ,y_train  )
print("train",score_train)

test 0.9204887313030036
train 0.9205543470511655
